### ISSUE TITLE
double cd statement in readme

### ISSUE THREAD

**Issue by Yochyo** [fusigi0930/switch_joystick_emu#1]
"cd ~/cd switch_joystick_emu/js_emu" should be "cd switch_joystick_emu/js_emu"
"cd ~/cd switch_joystick_emu" should be "cd switch_joystick_emu"

**Comment by Yochyo** [comment]
if this is meant to navigate to home then to the corresponding subfolder, this is at least not possible with my raspberry

**Comment by fusigi0930** [comment]
do you make js_emu first?, the first change directory just make the js_emu project.
if you don't want to change directory, you can use the command:
make -C <js_emu directory in your file system>, it also can build the project.

notice: cd ~/ >== is the normal case in linux system, that means cd $HOME/,
cd ~/... is changing to a absolute path, please don't lost the the prefix words while you type these commands
